{{- if .serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .serviceAccount.name }}
  labels:
    {{- include "bookinfo.labels" $ | nindent 4 }}
    account: {{ .serviceName }}
{{- end -}}